/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppSearch {
    }
    interface ItemGrid {
        "items": any[];
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSearchElement extends Components.AppSearch, HTMLStencilElement {
    }
    var HTMLAppSearchElement: {
        prototype: HTMLAppSearchElement;
        new (): HTMLAppSearchElement;
    };
    interface HTMLItemGridElement extends Components.ItemGrid, HTMLStencilElement {
    }
    var HTMLItemGridElement: {
        prototype: HTMLItemGridElement;
        new (): HTMLItemGridElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-search": HTMLAppSearchElement;
        "item-grid": HTMLItemGridElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppSearch {
    }
    interface ItemGrid {
        "items"?: any[];
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-search": AppSearch;
        "item-grid": ItemGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-search": LocalJSX.AppSearch & JSXBase.HTMLAttributes<HTMLAppSearchElement>;
            "item-grid": LocalJSX.ItemGrid & JSXBase.HTMLAttributes<HTMLItemGridElement>;
        }
    }
}
