/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppPodcast {
        "match": MatchResults;
        "podcast": any;
    }
    interface AppRoot {
    }
    interface AppSearch {
    }
    interface AppSubscriptions {
    }
    interface ItemGrid {
        "items": any[];
    }
}
declare global {
    interface HTMLAppPodcastElement extends Components.AppPodcast, HTMLStencilElement {
    }
    var HTMLAppPodcastElement: {
        prototype: HTMLAppPodcastElement;
        new (): HTMLAppPodcastElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSearchElement extends Components.AppSearch, HTMLStencilElement {
    }
    var HTMLAppSearchElement: {
        prototype: HTMLAppSearchElement;
        new (): HTMLAppSearchElement;
    };
    interface HTMLAppSubscriptionsElement extends Components.AppSubscriptions, HTMLStencilElement {
    }
    var HTMLAppSubscriptionsElement: {
        prototype: HTMLAppSubscriptionsElement;
        new (): HTMLAppSubscriptionsElement;
    };
    interface HTMLItemGridElement extends Components.ItemGrid, HTMLStencilElement {
    }
    var HTMLItemGridElement: {
        prototype: HTMLItemGridElement;
        new (): HTMLItemGridElement;
    };
    interface HTMLElementTagNameMap {
        "app-podcast": HTMLAppPodcastElement;
        "app-root": HTMLAppRootElement;
        "app-search": HTMLAppSearchElement;
        "app-subscriptions": HTMLAppSubscriptionsElement;
        "item-grid": HTMLItemGridElement;
    }
}
declare namespace LocalJSX {
    interface AppPodcast {
        "match"?: MatchResults;
        "podcast"?: any;
    }
    interface AppRoot {
    }
    interface AppSearch {
    }
    interface AppSubscriptions {
    }
    interface ItemGrid {
        "items"?: any[];
    }
    interface IntrinsicElements {
        "app-podcast": AppPodcast;
        "app-root": AppRoot;
        "app-search": AppSearch;
        "app-subscriptions": AppSubscriptions;
        "item-grid": ItemGrid;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-podcast": LocalJSX.AppPodcast & JSXBase.HTMLAttributes<HTMLAppPodcastElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-search": LocalJSX.AppSearch & JSXBase.HTMLAttributes<HTMLAppSearchElement>;
            "app-subscriptions": LocalJSX.AppSubscriptions & JSXBase.HTMLAttributes<HTMLAppSubscriptionsElement>;
            "item-grid": LocalJSX.ItemGrid & JSXBase.HTMLAttributes<HTMLItemGridElement>;
        }
    }
}
